---
- hosts: webservers
  become: yes
  tasks:
  - name: Install httpd package
    yum:
      name: httpd
      state: latest

  - name: Enable and Start httpd service
    service:
      name: httpd
      state: started
      enabled: yes

  - name: Create index.html file for hosting static content
    copy:
      content: "Horrryaaayyy!!!! My First Playbook ran sucessfully"
      dest: /var/www/html/index.html
